export const SUBMIT_PHOTO_START = 'SUBMIT_PHOTO_START';
export const SUBMIT_PHOTO_SUCCESS = 'SUBMIT_PHOTO_SUCCESS';
export const SUBMIT_PHOTO_FAIL = 'SUBMIT_PHOTO_FAIL';

export const UPLOAD_PHOTO_START = 'UPLOAD_PHOTO_START';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_FAIL = 'UPLOAD_PHOTO_FAIL';

export const FETCH_ALL_PHOTOS = 'FETCH_ALL_PHOTOS';
export const FETCH_ALL_PHOTOS_START = 'FETCH_ALL_PHOTOS_START';
export const FETCH_ALL_PHOTOS_SUCCESS = 'FETCH_ALL_PHOTOS_SUCCESS';
export const FETCH_USER_PHOTOS = 'FETCH_USER_PHOTOS';
export const FETCH_USER_PHOTOS_START = 'FETCH_USER_PHOTOS_START';
export const FETCH_USER_PHOTOS_SUCCESS = 'FETCH_USER_PHOTOS_SUCCESS';
export const FETCH_FRIENDS_PHOTOS = 'FETCH_FRIENDS_PHOTOS';
export const FETCH_FRIENDS_PHOTOS_START = 'FETCH_FRIENDS_PHOTOS_START';
export const FETCH_FRIENDS_PHOTOS_SUCCESS = 'FETCH_FRIENDS_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';
export const FETCH_FOLLOWINGS = 'FETCH_FOLLOWINGS';
export const FETCH_FOLLOWINGS_START = 'FETCH_FOLLOWINGS_START';
export const FETCH_FOLLOWINGS_SUCCESS = 'FETCH_FOLLOWINGS_SUCCESS';
export const FETCH_FOLLOWINGS_FAIL = 'FETCH_FOLLOWINGS_FAIL';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
