export const UPLOAD_INIT = 'UPLOAD_INIT';
export const UPLOAD_PHOTO_START = 'UPLOAD_PHOTO_START';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_FAIL = 'UPLOAD_PHOTO_FAIL';

export const FETCH_ALL_PHOTOS = 'FETCH_ALL_PHOTOS';
export const FETCH_ALL_PHOTOS_START = 'FETCH_ALL_PHOTOS_START';
export const FETCH_ALL_PHOTOS_SUCCESS = 'FETCH_ALL_PHOTOS_SUCCESS';
export const FETCH_SINGLE_PHOTO = 'FETCH_SINGLE_PHOTO';
export const FETCH_SINGLE_PHOTO_START = 'FETCH_SINGLE_PHOTO_START';
export const FETCH_SINGLE_PHOTO_SUCCESS = 'FETCH_SINGLE_PHOTO_SUCCESS';
export const FETCH_USER_PHOTOS = 'FETCH_USER_PHOTOS';
export const FETCH_USER_PHOTOS_START = 'FETCH_USER_PHOTOS_START';
export const FETCH_USER_PHOTOS_SUCCESS = 'FETCH_USER_PHOTOS_SUCCESS';

export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';
